<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<AssemblyName>nomad_iis</AssemblyName>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
		<Product>Windows IIS Driver for HashiCorp Nomad</Product>
		<ProductName>Windows IIS Driver for HashiCorp Nomad</ProductName>
		<Copyright>(C) Copyright 2025, Daniel Peinhopf</Copyright>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<DefineConstants>MANAGEMENT_API;$(DefineConstants)</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Grpc.AspNetCore" />
		<PackageReference Include="Grpc.AspNetCore.HealthChecks" />
		<PackageReference Include="Grpc.AspNetCore.Server.Reflection" />
		<PackageReference Include="MessagePack" />
		<PackageReference Include="Microsoft.Web.Administration" />
		<PackageReference Include="Serilog.AspNetCore" />
	</ItemGroup>

	<ItemGroup Condition="$(DefineConstants.Contains('MANAGEMENT_API'))">
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" />
		<PackageReference Include="Microsoft.Playwright" />
		<PackageReference Include="CliWrap" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>$(ProjectName).Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="**/*.proto" GrpcServices="Server" />
	</ItemGroup>

</Project>
